on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test without coverage
        if: matrix.os == 'windows-latest'
        run:  go test -v -race -count=1 -coverprofile=coverage.out ./...
      - name: Test with coverage
        if: matrix.os != 'windows-latest'
        run:  go test -v -race -count=1 -coverprofile=coverage.out ./...
      - name: Upload coverage report
        run: (curl -s https://codecov.io/bash) | bash
